# Generated by Django 3.1.2 on 2020-11-02 18:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(blank=True, max_length=150)),
                ('about_details', models.TextField(blank=True, max_length=1000)),
                ('about_images', models.ImageField(blank=True, upload_to='about')),
                ('is_published', models.BooleanField(default=True)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieve_title', models.CharField(blank=True, max_length=150)),
                ('achieve_number', models.CharField(blank=True, max_length=150)),
                ('is_published', models.BooleanField(default=True)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievement',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_headline', models.CharField(blank=True, max_length=300)),
                ('blog_details', models.CharField(blank=True, max_length=1500)),
                ('blog_images', models.ImageField(upload_to='blog')),
                ('is_published', models.BooleanField(default=True)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blog',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=30)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True, max_length=1000)),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='logo')),
                ('company_name', models.CharField(blank=True, max_length=50)),
                ('slider_headline', models.CharField(blank=True, max_length=150)),
                ('slider_small_headline', models.TextField(blank=True, max_length=800)),
                ('slider_images', models.ImageField(blank=True, upload_to='slider')),
                ('is_published', models.BooleanField(default=True)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Home',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_one', models.CharField(blank=True, max_length=150)),
                ('process_title_one', models.CharField(blank=True, max_length=150)),
                ('process_details_one', models.TextField(blank=True, max_length=250)),
                ('icon_two', models.CharField(blank=True, max_length=150)),
                ('process_title_two', models.CharField(blank=True, max_length=150)),
                ('process_details_two', models.TextField(blank=True, max_length=250)),
                ('icon_three', models.CharField(blank=True, max_length=150)),
                ('process_title_three', models.CharField(blank=True, max_length=150)),
                ('process_details_three', models.TextField(blank=True, max_length=250)),
                ('icon_four', models.CharField(blank=True, max_length=150)),
                ('process_title_four', models.CharField(blank=True, max_length=150)),
                ('process_details_four', models.TextField(blank=True, max_length=250)),
                ('is_published', models.BooleanField(default=True)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Process',
                'verbose_name_plural': 'Process',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('col-md-5 img js-fullheight', 'Left'), ('col-md-5 order-md-last img js-fullheight', 'Right')], max_length=100)),
                ('projects_title', models.CharField(blank=True, max_length=250)),
                ('projects_details', models.CharField(blank=True, max_length=1000)),
                ('projects_images', models.ImageField(upload_to='projects')),
                ('is_published', models.BooleanField(default=True)),
                ('projects_headline', models.CharField(blank=True, max_length=150)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Projects',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_title', models.CharField(blank=True, max_length=150)),
                ('services_details', models.TextField(blank=True, max_length=300)),
                ('icon', models.CharField(blank=True, max_length=200)),
                ('is_published', models.BooleanField(default=True)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Services',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='StaticContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_page_image', models.ImageField(upload_to='about')),
                ('about_page_headline', models.CharField(blank=True, max_length=500)),
                ('team_page_image', models.ImageField(upload_to='team')),
                ('team_page_headline', models.CharField(blank=True, max_length=500)),
                ('service_page_image', models.ImageField(upload_to='service')),
                ('service_page_headline', models.CharField(blank=True, max_length=500)),
                ('project_page_image', models.ImageField(upload_to='project')),
                ('project_page_headline', models.CharField(blank=True, max_length=500)),
                ('blog_page_image', models.ImageField(upload_to='blog')),
                ('blog_page_headline', models.CharField(blank=True, max_length=500)),
                ('contact_page_image', models.ImageField(upload_to='contact')),
                ('contact_page_headline', models.CharField(blank=True, max_length=500)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Static Content',
                'verbose_name_plural': 'Static Content',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('images', models.ImageField(upload_to='team')),
                ('linkedin', models.CharField(blank=True, max_length=300)),
                ('facebook', models.CharField(blank=True, max_length=300)),
                ('twitter', models.CharField(blank=True, max_length=300)),
                ('is_published', models.BooleanField(default=True)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Team',
            },
        ),
    ]
