# Generated by Django 3.1.2 on 2020-10-31 17:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(blank=True, max_length=150)),
                ('about_details', models.TextField(blank=True, max_length=250)),
                ('about_images', models.ImageField(upload_to='about')),
                ('achieve_title_one', models.CharField(blank=True, max_length=150)),
                ('achieve_number_one', models.CharField(blank=True, max_length=150)),
                ('achieve_title_two', models.CharField(blank=True, max_length=150)),
                ('achieve_number_two', models.CharField(blank=True, max_length=150)),
                ('achieve_title_three', models.CharField(blank=True, max_length=150)),
                ('achieve_number_three', models.CharField(blank=True, max_length=150)),
                ('achieve_title_four', models.CharField(blank=True, max_length=150)),
                ('achieve_number_four', models.CharField(blank=True, max_length=150)),
                ('is_published', models.BooleanField(default=True)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_headline', models.CharField(blank=True, max_length=300)),
                ('blog_details', models.CharField(blank=True, max_length=1500)),
                ('blog_images', models.ImageField(upload_to='blog')),
                ('is_published', models.BooleanField(default=True)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=35)),
                ('subject', models.EmailField(blank=True, max_length=200)),
                ('message', models.EmailField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo')),
                ('slider_headline', models.CharField(blank=True, max_length=150)),
                ('slider_small_headline', models.CharField(blank=True, max_length=150)),
                ('slider_images', models.ImageField(blank=True, upload_to='slider')),
                ('is_published', models.BooleanField(default=True)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo')),
                ('process_title', models.CharField(blank=True, max_length=150)),
                ('process_details', models.TextField(blank=True, max_length=250)),
                ('is_published', models.BooleanField(default=True)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects_title', models.CharField(blank=True, max_length=250)),
                ('projects_details', models.CharField(blank=True, max_length=1000)),
                ('projects_images', models.ImageField(upload_to='projects')),
                ('is_published', models.BooleanField(default=True)),
                ('projects_headline', models.CharField(blank=True, max_length=150)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_title', models.CharField(blank=True, max_length=150)),
                ('services_details', models.TextField(blank=True, max_length=300)),
                ('logo', models.ImageField(upload_to='logo')),
                ('is_published', models.BooleanField(default=True)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('images', models.ImageField(upload_to='team')),
                ('linkedin', models.CharField(blank=True, max_length=300)),
                ('facebook', models.CharField(blank=True, max_length=300)),
                ('is_published', models.BooleanField(default=True)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
