# Generated by Django 3.1.2 on 2020-10-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcms', '0002_home_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='process_title',
            new_name='icon',
        ),
        migrations.RemoveField(
            model_name='process',
            name='logo',
        ),
        migrations.AlterField(
            model_name='home',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logo'),
        ),
    ]
