# Generated by Django 3.1.2 on 2020-11-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcms', '0002_auto_20201103_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_details_one',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_details_two',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_headline_one',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_headline_two',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_images',
            field=models.ImageField(blank=True, upload_to='blog'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_images_two',
            field=models.ImageField(blank=True, upload_to='blog'),
        ),
    ]
