# Generated by Django 3.1.2 on 2020-10-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcms', '0003_auto_20201031_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='process_title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
