# Generated by Django 3.1.2 on 2020-11-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcms', '0004_auto_20201103_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='blog',
            name='author_comment',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='blog',
            name='author_images',
            field=models.ImageField(blank=True, upload_to='author'),
        ),
    ]
