# Generated by Django 3.1.2 on 2020-10-31 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcms', '0005_auto_20201031_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='icon_four',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='process',
            name='icon_three',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='process',
            name='process_details_four',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='process',
            name='process_details_three',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='process',
            name='process_title_four',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='process',
            name='process_title_three',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
