# Generated by Django 3.1.2 on 2020-10-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcms', '0006_auto_20201031_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='process_details_one',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
