# Generated by Django 3.1.2 on 2020-11-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcms', '0006_auto_20201103_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author_comment',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
