# Generated by Django 3.1.2 on 2020-11-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcms', '0007_auto_20201103_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_link_one', models.CharField(blank=True, max_length=50)),
                ('nav_link_two', models.CharField(blank=True, max_length=50)),
                ('nav_link_three', models.CharField(blank=True, max_length=50)),
                ('nav_link_four', models.CharField(blank=True, max_length=50)),
                ('nav_link_five', models.CharField(blank=True, max_length=50)),
                ('nav_link_six', models.CharField(blank=True, max_length=50)),
                ('nav_link_seven', models.CharField(blank=True, max_length=50)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Navbar',
                'verbose_name_plural': 'Navbar',
            },
        ),
    ]
