# Generated by Django 3.1.2 on 2020-10-31 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcms', '0007_process_process_details_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_details',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
