# Generated by Django 3.1.2 on 2020-10-31 19:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webcms', '0008_auto_20201031_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieve_title_one', models.CharField(blank=True, max_length=150)),
                ('achieve_number_one', models.CharField(blank=True, max_length=150)),
                ('achieve_title_two', models.CharField(blank=True, max_length=150)),
                ('achieve_number_two', models.CharField(blank=True, max_length=150)),
                ('achieve_title_three', models.CharField(blank=True, max_length=150)),
                ('achieve_number_three', models.CharField(blank=True, max_length=150)),
                ('achieve_title_four', models.CharField(blank=True, max_length=150)),
                ('achieve_number_four', models.CharField(blank=True, max_length=150)),
                ('is_published', models.BooleanField(default=True)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='achieve_number_four',
        ),
        migrations.RemoveField(
            model_name='about',
            name='achieve_number_one',
        ),
        migrations.RemoveField(
            model_name='about',
            name='achieve_number_three',
        ),
        migrations.RemoveField(
            model_name='about',
            name='achieve_number_two',
        ),
        migrations.RemoveField(
            model_name='about',
            name='achieve_title_four',
        ),
        migrations.RemoveField(
            model_name='about',
            name='achieve_title_one',
        ),
        migrations.RemoveField(
            model_name='about',
            name='achieve_title_three',
        ),
        migrations.RemoveField(
            model_name='about',
            name='achieve_title_two',
        ),
        migrations.AlterField(
            model_name='about',
            name='about_images',
            field=models.ImageField(blank=True, upload_to='about'),
        ),
    ]
