# Generated by Django 3.1.2 on 2020-10-31 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcms', '0009_auto_20201031_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='achieve_number_four',
            new_name='achieve_number',
        ),
        migrations.RenameField(
            model_name='achievement',
            old_name='achieve_number_one',
            new_name='achieve_title',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='achieve_number_three',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='achieve_number_two',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='achieve_title_four',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='achieve_title_one',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='achieve_title_three',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='achieve_title_two',
        ),
    ]
