# Generated by Django 3.1.2 on 2020-11-13 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcms', '0011_auto_20201113_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='nav_link_seven',
        ),
    ]
