# Generated by Django 3.1.2 on 2020-11-13 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcms', '0012_remove_footer_nav_link_seven'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='nav_link_five',
            new_name='nav_link_about',
        ),
        migrations.RenameField(
            model_name='footer',
            old_name='nav_link_four',
            new_name='nav_link_blog',
        ),
        migrations.RenameField(
            model_name='footer',
            old_name='nav_link_one',
            new_name='nav_link_contact',
        ),
        migrations.RenameField(
            model_name='footer',
            old_name='nav_link_six',
            new_name='nav_link_project',
        ),
        migrations.RenameField(
            model_name='footer',
            old_name='nav_link_three',
            new_name='nav_link_services',
        ),
        migrations.RenameField(
            model_name='footer',
            old_name='nav_link_two',
            new_name='nav_link_team',
        ),
    ]
