# Generated by Django 3.1.2 on 2020-11-13 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcms', '0014_auto_20201113_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navbar',
            old_name='nav_link_five',
            new_name='about_nav_link',
        ),
        migrations.RenameField(
            model_name='navbar',
            old_name='nav_link_four',
            new_name='blog_nav_link',
        ),
        migrations.RenameField(
            model_name='navbar',
            old_name='nav_link_one',
            new_name='community_nav_link',
        ),
        migrations.RenameField(
            model_name='navbar',
            old_name='nav_link_seven',
            new_name='contact_link',
        ),
        migrations.RenameField(
            model_name='navbar',
            old_name='nav_link_six',
            new_name='home_nav_link',
        ),
        migrations.RenameField(
            model_name='navbar',
            old_name='nav_link_three',
            new_name='projects_nav_link',
        ),
        migrations.RenameField(
            model_name='navbar',
            old_name='nav_link_two',
            new_name='services_nav_link',
        ),
    ]
