# Generated by Django 3.1.2 on 2020-11-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcms', '0015_auto_20201113_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='icon_images',
            field=models.ImageField(blank=True, upload_to='icon'),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_details',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author_comment',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_details_one',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_headline_two',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='home',
            name='slider_headline',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='about_nav_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='blog_nav_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='community_nav_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='contact_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='home_nav_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='projects_nav_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='services_nav_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_details_four',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_details_one',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_details_three',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_details_two',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_title_four',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_title_one',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_title_three',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_title_two',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='projects',
            name='position',
            field=models.CharField(choices=[('col-md-5 img js-fullheight', 'Left'), ('col-md-5 order-md-last img js-fullheight', 'Right')], max_length=500),
        ),
        migrations.AlterField(
            model_name='projects',
            name='projects_details',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='projects',
            name='projects_headline',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='projects',
            name='projects_title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='services',
            name='services_details',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='services',
            name='services_title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
