# Generated by Django 3.1.2 on 2020-11-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcms', '0016_auto_20201117_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='icon_images',
            new_name='icon_image_four',
        ),
        migrations.RemoveField(
            model_name='process',
            name='icon_four',
        ),
        migrations.RemoveField(
            model_name='process',
            name='icon_one',
        ),
        migrations.RemoveField(
            model_name='process',
            name='icon_three',
        ),
        migrations.RemoveField(
            model_name='process',
            name='icon_two',
        ),
        migrations.AddField(
            model_name='process',
            name='icon_image_one',
            field=models.ImageField(blank=True, upload_to='icon'),
        ),
        migrations.AddField(
            model_name='process',
            name='icon_image_three',
            field=models.ImageField(blank=True, upload_to='icon'),
        ),
        migrations.AddField(
            model_name='process',
            name='icon_image_two',
            field=models.ImageField(blank=True, upload_to='icon'),
        ),
    ]
