# Generated by Django 3.1.2 on 2020-11-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcms', '0018_projects_icon_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='icon_reference',
            field=models.CharField(choices=[('mh-id-1', '1'), ('mh-id-2', '2'), ('mh-id-3', '3'), ('mh-id-4', '4')], max_length=500, null=True),
        ),
    ]
